### ISSUE TITLE
Where is the 'downloads' section for the HDF5 database?

### ISSUE THREAD

**Issue by Aerlinger** [johnglover/modal#4]
The readme mentions a downloadable HDF5 database not included with the repository, but I can't find the mentioned downloads section or anything in the doc. Perhaps the Readme is out of date?

**Comment by Aerlinger** [comment]
Is this it: http://dl.dropbox.com/u/9444913/onsets1.1.hdf5?

**Comment by johnglover** [comment]
Yes sorry, I think that is the most recent version (there used to be a downloads section on Github).

**Comment by rockyplum** [comment]
![image](https://user-images.githubusercontent.com/24423434/29632864-25eb929c-87f9-11e7-8db6-ca6ee864e0c8.png)

**Comment by johnglover** [comment]
Sorry, Dropbox also removed public sharing. Now on Google Drive: https://drive.google.com/file/d/1NA_QZ7r8fpl6xqmnCvPArv5Zo-70GFu9/view?usp=sharing
